name: CI

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ⬇️ Устанавливем pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Verify pnpm
        run: pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Unit tests (API)
        run: pnpm -F api test

      - name: Unit tests (WEB)
        run: pnpm -F web test

      - name: Build (API)
        run: pnpm -F api build

      - name: Build (WEB)
        env:
          NEXT_PUBLIC_APP_ENV: dev
        run: pnpm -F web build
